### ISSUE TITLE
Equality Explorer: Two Variables - master checklist 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer-two-variables#1]
NOTE: This sim is a specialization of the _Variables_ screen from equality-explorer. Checklist items marked as "N/A" (not applicable) will be skipped or handled as part of the equality-explorer checklist.

## Design
- [x] **Sim folder and design doc created** (N/A)
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account (N/A)
  - [x] Place design doc in the sim folder (N/A)
- [x] **Sim suggestions doc reviewed** (N/A)
- [x] **Learning goals and standards identified** (N/A)
- [x] **Design concept complete**  (N/A)
- [x] **Wireframes complete** (N/A)
- [x] **Mockups complete** (N/A)
  - [x] Mockups checked for colorblind and greyscale (N/A)
- [x] **Features for PhET-iO discussion** (N/A)
- [x] **Interviews complete** (N/A)
- [x] **Lead designer "sign off"** (N/A)
- [ ] **Pre-publication items**
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Sim primer draft
  - [ ] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [ ] [LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [ ] **Post-publication items**
  - [x] Add to Edmodo
  - [x] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  - [ ] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)

## Implementation
- [x] **Repository created** (Date: 5/24/18)
  - [x] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] Use `grunt create-sim` in perennial (see `--help` for arguments) to create the repository structure
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos
- [x] **Development started** (N/A)
- [x] **Sim is "feature complete"** (Date: 5/24/18)
- [x] **Code review completed** (N/A)
- [x] **Pre-publication items**
  - [x] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)  - see phetsims/equality-explorer#125
  - [x] Verify credits - see phetsims/equality-explorer#2
- [x] **Published** (Date: 7/18/18)
  - [x] README.md updated using `grunt published-README` (in master and release branch)
  - [x] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)

## QA
- [x] **Dev testing started** (Date: 6/18/18) 
- [x] **Dev testing completed** (Date: 7/5/18) 
- [x] **First RC published** (Date: 7/13/18)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 7/17/18)

**Comment by pixelzoom** [comment]
All remaining checklist items are for @amanda-phet to complete.

**Comment by pixelzoom** [comment]
Lots of checklist items remain here, and this sim has been published for awhile.  @amanda-phet @ariel-phet can you please review?

**Comment by pixelzoom** [comment]
@ariel-phet @amanda-phet Should remaining checklist items be split out into their own issues?

**Comment by amanda-phet** [comment]
I already made an issue for the primer (which will be a while before I get to it) and the LoL icons may or may not happen, depending on which math sims LoL is going to support. So the only remaining items are for @ariel-phet (edmodo, guru, etc.). 

(As an aside, I think we need to remove "add an activity" from this checklist. I have never once written a sim-based activity for a sim before publication. The primer draft is reasonable to make an issue about, but I have also not completed this before publication because I'm still catching up on primers for already-published sims.)

**Comment by pixelzoom** [comment]
@amanda-phet said:
> As an aside, I think we need to remove "add an activity" from this checklist.  ...

Noted in https://github.com/phetsims/phet-info/issues/86.

**Comment by arouinfar** [comment]
@amanda-phet LoL is supposed to expand their platform to include math in early 2019 (though this date has been pushed back before). There's no point in spending time on LoL icons/metadata for this sim yet, so I would open a separate issue for that work and leave it as `status:on-hold` (or unassigned) until it becomes relevant. You might want to do the same for other math sims which have been tested in the LoL harness. (So far, I think that's only been the Area Model suite & GQ.)

**Comment by ariel-phet** [comment]
created a deferred LoL issue #5

**Comment by ariel-phet** [comment]
Relevant issues created for remaining items, closing
